
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package My_Forms;

import java.awt.Color;
import java.util.ArrayList;

import javax.swing.BorderFactory;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aayush
 */
public class AuthorsListForm extends javax.swing.JFrame {

        My_classes.Author author = new My_classes.Author();
        public String formType = "";
        /**
         * Creates new form ManageAuthorsForm
         */
        public AuthorsListForm() {
                initComponents();

                this.setLocationRelativeTo(null);
                Border panelHeaderBorder = BorderFactory.createMatteBorder(3, 3, 3, 3, new Color(1, 50, 67));
                jPanel1.setBorder(panelHeaderBorder);

                My_classes.Func_Class func = new My_classes.Func_Class();

                func.displayImage(75, 60,null, "/My_Image/notepad_pencil.png", jLabel_FormTitle);

                func.customTable(jTable_Authors_);

                func.customTableHeader(jTable_Authors_, new Color(34, 167, 240), 16);

       
                 populateJtableWithAuthors();

        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_FormTitle = new javax.swing.JLabel();
        jLabel_CloseForm_ = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Genres_ = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_Authors_ = new javax.swing.JTable();
        jButton_Select_Author_ = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jPanel1ComponentAdded(evt);
            }
        });

        jLabel_FormTitle.setBackground(new java.awt.Color(1, 50, 67));
        jLabel_FormTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_FormTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_FormTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_FormTitle.setText("Manage Authors");
        jLabel_FormTitle.setOpaque(true);

        jLabel_CloseForm_.setBackground(new java.awt.Color(1, 50, 67));
        jLabel_CloseForm_.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel_CloseForm_.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_CloseForm_.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_CloseForm_.setText("X");
        jLabel_CloseForm_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_CloseForm_.setOpaque(true);
        jLabel_CloseForm_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CloseForm_MouseClicked(evt);
            }
        });

        jTable_Genres_.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTable_Genres_.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_Genres_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_Genres_MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Genres_);

        jTable_Authors_.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable_Authors_.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable_Authors_);

        jButton_Select_Author_.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jButton_Select_Author_.setText("Select Author");
        jButton_Select_Author_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Select_Author_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_FormTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_CloseForm_, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton_Select_Author_, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(774, 774, 774)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_FormTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_CloseForm_, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 364, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Select_Author_, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_Select_Author_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Select_Author_ActionPerformed
        int index = jTable_Authors_.getSelectedRow();
        int id = Integer.parseInt(jTable_Authors_.getValueAt(index, 0).toString());
        String firstName = jTable_Authors_.getValueAt(index, 1).toString();
        String lastName = jTable_Authors_.getValueAt(index, 2).toString();
                
        String full_name = firstName +" "+lastName;
        
        if(formType.equals("edit"))
        EditBookForm.displayAuthorData(id, full_name);
        else
        AddBookForm.displayAuthorData(id, full_name);
        //close this form
        this.dispose();
    }//GEN-LAST:event_jButton_Select_Author_ActionPerformed

        private void jPanel1ComponentAdded(java.awt.event.ContainerEvent evt) {// GEN-FIRST:event_jPanel1ComponentAdded
                // TODO add your handling code here:
        }// GEN-LAST:event_jPanel1ComponentAdded

        private void jTextArea_AboutActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextArea_AboutActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_jTextArea_AboutActionPerformed

        private void jTextField_AboutActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField_AboutActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_jTextField_AboutActionPerformed

        private void jLabel_EmptyLastName_MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel_EmptyLastName_MouseClicked

                jLabel_EmptyLastName_.setVisible(false);

        }// GEN-LAST:event_jLabel_EmptyLastName_MouseClicked

        private void jTextField_ExpertiseActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField_ExpertiseActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_jTextField_ExpertiseActionPerformed

        private void jTextField_LastNameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField_LastNameActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_jTextField_LastNameActionPerformed

        private void jTable_Authors_MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jTable_Authors_MouseClicked
         
        }// GEN-LAST:event_jTable_Authors_MouseClicked


        private void jTextField_FirstNameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField_FirstNameActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_jTextField_FirstNameActionPerformed

        
        private void jTable_Genres_MouseClicked(java.awt.event.MouseEvent evt) {
            // Logic to handle mouse click on jTable_Genres
}
        
        
        private void jTextField_IDActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField_IDActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_jTextField_IDActionPerformed

        private void jLabel_CloseForm_MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel_CloseForm_MouseClicked
                this.dispose();

        }// GEN-LAST:event_jLabel_CloseForm_MouseClicked

        private void jTable_Authors_ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTable_Authors_ActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_jTable_Authors_ActionPerformed

        public void populateJtableWithAuthors() {
                ArrayList<My_classes.Author> authorsList = author.authorsList();

                String[] colNames = { "ID", "F-Name", "L-Name", "Expertise", "About" };
                Object[][] rows = new Object[authorsList.size()][colNames.length];

                for (int i = 0; i < authorsList.size(); i++) {
                        rows[i][0] = authorsList.get(i).getId();
                        rows[i][1] = authorsList.get(i).getFirstName();
                        rows[i][2] = authorsList.get(i).getLastName();
                        rows[i][3] = authorsList.get(i).getField_Of_Expertise();
                        rows[i][4] = authorsList.get(i).getAbout();
                }

                DefaultTableModel model = new DefaultTableModel(rows, colNames);
                jTable_Authors_.setModel(model);
        }

        public static void main(String args[]) {

                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        // javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        javax.swing.UIManager.setLookAndFeel(
                                                        javax.swing.UIManager.getSystemLookAndFeelClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(AuthorsListForm.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(AuthorsListForm.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(AuthorsListForm.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(AuthorsListForm.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                }
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new AuthorsListForm().setVisible(true);
                        }
                });
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Select_Author_;
    private javax.swing.JLabel jLabel_CloseForm_;
    private javax.swing.JLabel jLabel_FormTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jTable_Authors_;
    private javax.swing.JTable jTable_Genres_;
    // End of variables declaration//GEN-END:variables
}