
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package My_Forms;

import java.awt.Color;
import java.util.ArrayList;

import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aayush
 */
public class ManageAuthorsForm extends javax.swing.JFrame {

        My_classes.Author author = new My_classes.Author();

        /**
         * Creates new form ManageAuthorsForm
         */
        public ManageAuthorsForm() {
                initComponents();

                this.setLocationRelativeTo(null);
                Border panelHeaderBorder = BorderFactory.createMatteBorder(3, 3, 3, 3, new Color(1, 50, 67));
                jPanel1.setBorder(panelHeaderBorder);

                My_classes.Func_Class func = new My_classes.Func_Class();

                func.displayImage(75, 60,null, "/My_Image/notepad_pencil.png", jLabel_FormTitle);

                func.customTable(jTable_Authors_);

                func.customTableHeader(jTable_Authors_, new Color(34, 167, 240), 16);

                // hide the jlabel "empty name message"
                jLabel_EmptyFirstName_.setVisible(false);
                jLabel_EmptyLastName_.setVisible(false);
                // populateJtableWithAuthors();

        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jLabel_FormTitle = new javax.swing.JLabel();
                jLabel_CloseForm_ = new javax.swing.JLabel();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jTextField_ID = new javax.swing.JTextField();
                jTextField_FirstName = new javax.swing.JTextField();
                jButtonAdd = new javax.swing.JButton();
                jButton_Edit_ = new javax.swing.JButton();
                jButton_Delete_ = new javax.swing.JButton();
                jScrollPane1 = new javax.swing.JScrollPane();
                jTable_Genres_ = new javax.swing.JTable();
                jLabel_EmptyFirstName_ = new javax.swing.JLabel();
                jTextField_LastName = new javax.swing.JTextField();
                jTextField_Expertise = new javax.swing.JTextField();
                jLabel_EmptyLastName_ = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();
                jTextArea_About = new javax.swing.JTextField();
                jScrollPane2 = new javax.swing.JScrollPane();
                jTable_Authors_ = new javax.swing.JTable();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setUndecorated(true);

                jPanel1.setBackground(new java.awt.Color(255, 255, 255));
                jPanel1.addContainerListener(new java.awt.event.ContainerAdapter() {
                        public void componentAdded(java.awt.event.ContainerEvent evt) {
                                jPanel1ComponentAdded(evt);
                        }
                });

                jLabel_FormTitle.setBackground(new java.awt.Color(1, 50, 67));
                jLabel_FormTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                jLabel_FormTitle.setForeground(new java.awt.Color(255, 255, 255));
                jLabel_FormTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel_FormTitle.setText("Manage Authors");
                jLabel_FormTitle.setOpaque(true);

                jLabel_CloseForm_.setBackground(new java.awt.Color(1, 50, 67));
                jLabel_CloseForm_.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
                jLabel_CloseForm_.setForeground(new java.awt.Color(255, 255, 255));
                jLabel_CloseForm_.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel_CloseForm_.setText("X");
                jLabel_CloseForm_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                jLabel_CloseForm_.setOpaque(true);
                jLabel_CloseForm_.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                jLabel_CloseForm_MouseClicked(evt);
                        }
                });

                jLabel1.setBackground(new java.awt.Color(255, 255, 255));
                jLabel1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
                jLabel1.setText("First Name:");

                jLabel2.setBackground(new java.awt.Color(255, 255, 255));
                jLabel2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
                jLabel2.setText("ID:");

                jTextField_ID.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
                jTextField_ID.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTextField_IDActionPerformed(evt);
                        }
                });

                jTextField_FirstName.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
                jTextField_FirstName.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTextField_FirstNameActionPerformed(evt);
                        }
                });

                jButtonAdd.setBackground(new java.awt.Color(240, 240, 240));
                jButtonAdd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                jButtonAdd.setText("Add");
                jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton_Add_ActionPerformed(evt);
                        }
                });

                jButton_Edit_.setBackground(new java.awt.Color(240, 240, 240));
                jButton_Edit_.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                jButton_Edit_.setText("Edit");
                jButton_Edit_.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton_Edit_ActionPerformed(evt);
                        }
                });

                jButton_Delete_.setBackground(new java.awt.Color(240, 240, 240));
                jButton_Delete_.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                jButton_Delete_.setText("Delete");
                jButton_Delete_.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton_Delete_ActionPerformed(evt);
                        }
                });

                jTable_Genres_.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
                jTable_Genres_.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {

                                },
                                new String[] {

                                }));
                jTable_Genres_.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                jTable_Authors_MouseClicked(evt);
                        }
                });
                jScrollPane1.setViewportView(jTable_Genres_);

                jLabel_EmptyFirstName_.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
                jLabel_EmptyFirstName_.setForeground(new java.awt.Color(252, 0, 0));
                jLabel_EmptyFirstName_.setText("Enter the first name");
                jLabel_EmptyFirstName_.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                jLabel_EmptyFirstName_MouseClicked(evt);
                        }
                });

                jTextField_LastName.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
                jTextField_LastName.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTextField_LastNameActionPerformed(evt);
                        }
                });

                jTextField_Expertise.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
                jTextField_Expertise.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTextField_ExpertiseActionPerformed(evt);
                        }
                });

                jLabel_EmptyLastName_.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
                jLabel_EmptyLastName_.setForeground(new java.awt.Color(252, 0, 0));
                jLabel_EmptyLastName_.setText("Enter the last name");
                jLabel_EmptyLastName_.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                jLabel_EmptyLastName_MouseClicked(evt);
                        }
                });

                jLabel3.setBackground(new java.awt.Color(255, 255, 255));
                jLabel3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
                jLabel3.setText("Last Name:");

                jLabel4.setBackground(new java.awt.Color(255, 255, 255));
                jLabel4.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
                jLabel4.setText("Expertise:");

                jLabel6.setBackground(new java.awt.Color(255, 255, 255));
                jLabel6.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
                jLabel6.setText("About:");

                jTextArea_About.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
                jTextArea_About.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTextArea_AboutActionPerformed(evt);
                        }
                });

                jTable_Authors_.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {

                                },
                                new String[] {

                                }));
                jScrollPane2.setViewportView(jTable_Authors_);

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(30, 30, 30)
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addComponent(jLabel2)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                .addComponent(jTextField_ID,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                131,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                false)
                                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                                .createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                                                .addComponent(jTextField_LastName,
                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                .addComponent(jTextField_FirstName))
                                                                                                                                .addComponent(jLabel_EmptyFirstName_,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                257,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addComponent(jLabel1)
                                                                                                                                .addComponent(jLabel3)
                                                                                                                                .addComponent(jLabel_EmptyLastName_,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                257,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addComponent(jLabel4)
                                                                                                                                .addComponent(jTextField_Expertise,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                301,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(jScrollPane2,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                434,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(428, 428, 428)
                                                                                                .addComponent(jScrollPane1,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                337,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(jPanel1Layout
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addComponent(jLabel6)
                                                                                                                .addGap(695, 695,
                                                                                                                                695))
                                                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                jPanel1Layout.createSequentialGroup()
                                                                                                                                .addComponent(jLabel_FormTitle,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                697,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                .addComponent(jLabel_CloseForm_,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                74,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addComponent(jTextArea_About,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                301,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addGap(452, 452,
                                                                                                                                452))
                                                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                jPanel1Layout.createSequentialGroup()
                                                                                                                                .addComponent(jButtonAdd,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                99,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                .addComponent(jButton_Edit_,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                93,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                .addComponent(jButton_Delete_,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                98,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(jLabel_CloseForm_,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                86,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel_FormTitle,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                86,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                false)
                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                                .createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                                                .addComponent(jLabel2,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                43,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addComponent(jTextField_ID,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                .addComponent(jLabel1,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                43,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                .addComponent(jTextField_FirstName,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                .addComponent(jLabel_EmptyFirstName_,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                29,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                .addComponent(jLabel3,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                43,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                .addComponent(jTextField_LastName,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                .addComponent(jLabel_EmptyLastName_,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                29,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                .addComponent(jLabel4,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                43,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                .addComponent(jTextField_Expertise,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                                                .addComponent(jLabel6,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                43,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                .addComponent(jTextArea_About,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                208,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                .addComponent(jScrollPane2)))
                                                                                                .addGap(21, 21, 21)
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(jButtonAdd,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                34,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(jButton_Edit_,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                34,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(jButton_Delete_,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                34,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                                                .addComponent(jScrollPane1,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                270,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addContainerGap()));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 777,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jPanel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 6, Short.MAX_VALUE)));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void jPanel1ComponentAdded(java.awt.event.ContainerEvent evt) {// GEN-FIRST:event_jPanel1ComponentAdded
                // TODO add your handling code here:
        }// GEN-LAST:event_jPanel1ComponentAdded

        private void jTextArea_AboutActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextArea_AboutActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_jTextArea_AboutActionPerformed

        private void jTextField_AboutActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField_AboutActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_jTextField_AboutActionPerformed

        private void jLabel_EmptyLastName_MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel_EmptyLastName_MouseClicked

                jLabel_EmptyLastName_.setVisible(false);

        }// GEN-LAST:event_jLabel_EmptyLastName_MouseClicked

        private void jTextField_ExpertiseActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField_ExpertiseActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_jTextField_ExpertiseActionPerformed

        private void jTextField_LastNameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField_LastNameActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_jTextField_LastNameActionPerformed

        private void jLabel_EmptyFirstName_MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel_EmptyFirstName_MouseClicked
                jLabel_EmptyFirstName_.setVisible(false);
        }// GEN-LAST:event_jLabel_EmptyFirstName_MouseClicked

        private void jTable_Authors_MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jTable_Authors_MouseClicked
                int index = jTable_Authors_.getSelectedRow();

                String id = jTable_Authors_.getValueAt(index, 0).toString();
                String firstName = jTable_Authors_.getValueAt(index, 1).toString();
                String lastName = jTable_Authors_.getValueAt(index, 2).toString();
                String expertise = jTable_Authors_.getValueAt(index, 3).toString();
                String about = jTable_Authors_.getValueAt(index, 4).toString();

                jTextField_ID.setText(id);
                jTextField_FirstName.setText(firstName);
                jTextField_LastName.setText(lastName);
                jTextField_Expertise.setText(expertise);
                jTextArea_About.setText(about);

        }// GEN-LAST:event_jTable_Authors_MouseClicked

        private void jButton_Add_ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton_Add_ActionPerformed
                String fname = jTextField_FirstName.getText();
                String lname = jTextField_LastName.getText();
                String expertise = jTextField_Expertise.getText();
                String about = jTextArea_About.getText();
                if (fname.isEmpty()) {
                        jLabel_EmptyFirstName_.setVisible(true);
                } else if (lname.isEmpty()) {
                        jLabel_EmptyLastName_.setVisible(true);
                } else {
                        author.addAuthor(fname, lname, expertise, about);
                        // populateJtableWithAuthors();
                }

        }// GEN-LAST:event_jButton_Add_ActionPerformed

        private void jButton_Delete_ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton_Delete_ActionPerformed
                try {
                        int id = Integer.parseInt(jTextField_ID.getText());
                        author.removeAuthor(id);

                        jTextField_ID.setText("");
                        jTextField_FirstName.setText("");
                        jTextField_LastName.setText("");
                        jTextField_Expertise.setText("");
                        jTextArea_About.setText("");

                } catch (NumberFormatException ex) {
                        JOptionPane.showMessageDialog(null, "Invalid Author ID" + ex.getMessage(), "error", 0);
                }

        }

        private void jButton_Edit_ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton_Edit_ActionPerformed
                String fname = jTextField_FirstName.getText();
                String lname = jTextField_FirstName.getText();
                String expertise = jTextField_FirstName.getText();
                String about = jTextArea_About.getText();

                if (fname.isEmpty()) {
                        jLabel_EmptyFirstName_.setVisible(true);

                } else if (lname.isEmpty()) {
                        jLabel_EmptyLastName_.setVisible(true);
                } else {
                        try {
                                int id = Integer.parseInt(jTextField_ID.getText());
                                author.editAuthor(id, fname, lname, expertise, about);
                        } catch (NumberFormatException ex) {
                                JOptionPane.showMessageDialog(null, "Invalid Genre ID" + ex.getMessage(), "error", 0);
                        }
                }

        }// GEN-LAST:event_jButton_Edit_ActionPerformed

        private void jTextField_FirstNameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField_FirstNameActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_jTextField_FirstNameActionPerformed

        private void jTextField_IDActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField_IDActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_jTextField_IDActionPerformed

        private void jLabel_CloseForm_MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel_CloseForm_MouseClicked
                this.dispose();

        }// GEN-LAST:event_jLabel_CloseForm_MouseClicked

        private void jTable_Authors_ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTable_Authors_ActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_jTable_Authors_ActionPerformed

        public void populateJtableWithAuthors() {
                ArrayList<My_classes.Author> authorsList = author.authorsList();

                String[] colNames = { "ID", "F-Name", "L-Name", "Expertise", "About" };
                Object[][] rows = new Object[authorsList.size()][colNames.length];

                for (int i = 0; i < authorsList.size(); i++) {
                        rows[i][0] = authorsList.get(i).getId();
                        rows[i][1] = authorsList.get(i).getFirstName();
                        rows[i][1] = authorsList.get(i).getLastName();
                        rows[i][1] = authorsList.get(i).getField_Of_Expertise();
                        rows[i][1] = authorsList.get(i).getAbout();
                }

                DefaultTableModel model = new DefaultTableModel(rows, colNames);
                jTable_Authors_.setModel(model);
        }

        public static void main(String args[]) {

                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        // javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        javax.swing.UIManager.setLookAndFeel(
                                                        javax.swing.UIManager.getSystemLookAndFeelClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(ManageAuthorsForm.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(ManageAuthorsForm.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(ManageAuthorsForm.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(ManageAuthorsForm.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                }
                // </editor-fold>
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new ManageAuthorsForm().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jButtonAdd;
        private javax.swing.JButton jButton_Delete_;
        private javax.swing.JButton jButton_Edit_;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel_CloseForm_;
        private javax.swing.JLabel jLabel_EmptyFirstName_;
        private javax.swing.JLabel jLabel_EmptyLastName_;
        private javax.swing.JLabel jLabel_FormTitle;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JTable jTable_Authors_;
        private javax.swing.JTable jTable_Genres_;
        private javax.swing.JTextField jTextArea_About;
        private javax.swing.JTextField jTextField_Expertise;
        private javax.swing.JTextField jTextField_FirstName;
        private javax.swing.JTextField jTextField_ID;
        private javax.swing.JTextField jTextField_LastName;
        // End of variables declaration//GEN-END:variables
}